### ISSUE TITLE
Solve Problem in python

### ISSUE THREAD

**Issue by LON3WO7F** [LON3WO7F/OpenSource-2020#1]
You Can Submit As Many Pull Requests As You Want As Long As All Of Them Are Unique And Useful Programs Written In **Python**.

**Comment by PranavAnand587** [comment]
Can I add a program for printing the Fibonacci series in Python??

**Comment by LON3WO7F** [comment]
@PranavAnand587  Yeah Sure,
Go ahead!

**Comment by itai192** [comment]
Should I add a small program that splits text into how many equal parts (as equal as it can) as you ask it to?

**Comment by MAHIMA01** [comment]
Please assign this issue to me, I can add Factorial problem in python. Thanks!

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this in Python and c++. Pls assign this to me
