### ISSUE TITLE
Solve Problem in Java

### ISSUE THREAD

**Issue by LON3WO7F** [LON3WO7F/OpenSource-2020#2]
You Can Submit As Many Pull Requests As You Want As Long As All Of Them Are Unique And Useful Programs Written In **Java**.

**Comment by Yasas4D** [comment]
Hi, I would love to contribute to this project.
Please assign me.. I'm doing bubble sort in java

**Comment by Yasas4D** [comment]
Hi please take the PR on
Implement BubbleSort in Java #29

**Comment by Yasas4D** [comment]
Hi please take the PR on
Implement InsertionSort in Java #31

**Comment by Yasas4D** [comment]
Hi, I implemented the Fibonacci series to a given number
Implement Fibonacci Series #43
Thank you
