### ISSUE TITLE
Solve Problem in any Language

### ISSUE THREAD

**Issue by LON3WO7F** [LON3WO7F/OpenSource-2020#6]

**Comment by Cosmeeeen** [comment]
Hello! What kind of code would fit this project? I couldn't find any indications or what the code should focus on, but I would be glad to help with this.

**Comment by LON3WO7F** [comment]
Hey @Cosmeeeen 
You can write any code in any language. 
Like you can write any sorting or searching program or any other. But it should not match any program which is already commited in this repo.


**Happy Hacking!**

**Comment by Cosmeeeen** [comment]
Thank you! I will start working on a few sorting algorithms in Python and C++

**Comment by Matrix278** [comment]
Hello, I added some PR of js, php algorithms: #9 , #11 , ready to be reviewed

**Comment by Cosmeeeen** [comment]
Hello! If we're done with our 4 hacktoberfest pull requests, should we still contribute with algorithms, or leave them for people who want to finish their pull requests too?

I could contribute some more, and would be glad to if it helps, but I don't want to take that opportunity away from other people who might benefit more from it. 

Also if there is any other way to help with this project without taking other people's opportunities, I would be glad to do so. 
Thank you again for creating this repository. 😄

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this in python and c++. Pls assign this to me

**Comment by Anurajeev** [comment]
i would like to contribute could you assign me this issue

**Comment by LON3WO7F** [comment]
> Hello! If we're done with our 4 hacktoberfest pull requests, should we still contribute with algorithms, or leave them for people who want to finish their pull requests too?
> 
> I could contribute some more, and would be glad to if it helps, but I don't want to take that opportunity away from other people who might benefit more from it.
> 
> Also if there is any other way to help with this project without taking other people's opportunities, I would be glad to do so.
> Thank you again for creating this repository. smile

Hey @Cosmeeeen.
It's totally upto you whether you want to contribute more in algo or leave it for others.


If you want you can check #4 issue.
You can **### contribute** to this.

**Comment by LON3WO7F** [comment]
> i would like to contribute could you assign me this issue

@Anurajeev Yeah sure,
Go Ahead!


Please read the guideline carefully before contributing.
